version: "3.9"
name: the_mentes

services:

  frontend:
    container_name: the_mentes_frontend
    restart: always
    build: ./apps/frontend
    ports:
      - "${FRONTEND_EXPOSE_PORT}:3000"
    networks:
      app_network:
        aliases:
          - frontend_host

  docs:
    container_name: the_mentes_docs
    restart: always
    build: ./apps/docs
    ports:
      - "${DOCS_EXPOSE_PORT}:80"
    networks:
      app_network:
        aliases:
          - docs_host

  admin:
    container_name: the_mentes_admin
    restart: always
    build: ./apps/admin
    ports:
      - "${ADMIN_EXPOSE_PORT}:80"
    networks:
      app_network:
        aliases:
          - admin_host

  api:
    container_name: the_mentes_api
    restart: always
    build: ./apps/api
    ports:
      - "${API_EXPOSE_PORT}:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_EXPOSE_PORT: ${DB_EXPOSE_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database
    networks:
      app_network:
        aliases:
          - api_host

  database:
    image: postgres:latest
    restart: always
    container_name: the_mentes_db
    ports:
      - "${DB_EXPOSE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./var/db_data:/var/lib/postgresql/data
    networks:
      app_network:
        aliases:
          - "${DB_HOST}"


networks:
  app_network:
    name: app_net
    driver: bridge
    ipam:
      driver: default
